### PR TITLE
Support additional layers

### LINKED ISSUE #25: [Feature Request] Easier extensibility with custom layers
Let me start by saying: I love what you have created with miryoku, it is excellent and I use it every day :+1: 

That said, I often want to have one or two extra layers on some of my keyboards and this is currently a bit tricky to maintain without just copying the generated code and modifying it.

A common modification that I want is to add extra layers between `BASE` and the seven top layers. An example would be a qwerty layer for games with non-rebindable keys or a "normal" layer that I can activate when someone else needs to use my keyboard (see e.g. https://github.com/manna-harbour/qmk_firmware/pull/24). Most keyboards have enough keys to put a toggle for such rarely used functionality but it's a bit annoying to maintain and rebase as a patch set on top of the _tangled_ miryoku C code.

I would love for something like `-DMIRYOKU_EXTRA_LAYERS="QWERTY, GML, GMR, "` or even `-DMIRYOKU_EXTRA_LAYERS="QWERTY, GML, GMR, GML_QWERTY, GMR_QWERTY, "` to work but I'm not sure this is even really doable without going through preprocessor hell.

One alternative that would be a lot easier to maintain would be to

1. Statically assign layer numbers for `NAVR`, `MOUR`, `MEDR`, `MBO`, `FUNL`, `NSL`, `NSSL`, leaving some space above and below (or maybe allow setting a define for where they start, so a user can assign custom layers either below or above).
2. Create defines for all of the different possible base layers (and `GML`/`GMR` combinations if you accept the linked PR)
3. Allow the user to insert the layers with another define

These would allow slotting in e.g. the mentioned qwerty layer above `BASE` by just specifying `-DMIRYOKU_EXTRA_LAYERS="[1] = MIRYOKU_TAPHOLD_QWERTY`. But the user would have to maintain the usable layer ranges manually.

Now that I've written it all down it seems a bit involved, but maybe you have some suggestions on how to do this. (Or if you think this should just not be part of `miryoku.org` then that's of course also fine)

### PR DESCRIPTION
**Pull request by moben**
For any layers A, B, ... specified via MIRYOKU_EXTRA_LAYERS (up to 8),

  [A] = LAYOUT_miryoku(MIRYOKU_TABLE_A),
  [B] = LAYOUT_miryoku(MIRYOKU_TABLE_B),
  ...

will be added between the base layer and the top miryoku layers.

The tables can either be defined by the user or the tables that miryoku
defines can be used by specifying e.g. 'QWERTY' for a qwerty layer.

Fixes manna-harbour/miryoku#17

Looking forward to what you think of this approach. It's quite flexible from my initial experience and didn't require too much preprocessor hackery to get working.

I didn't touch the "upper" layers as I feel swapping in an extra flipped MEDIA layer is less useful than other layouts or user defined layers but it would be a simple mechanical change to add defines for the other layers. I'm just not sure how qmk handles it if the thumb key that switches the layer is remapped on the target layer.

### CODE REVIEW

**Comment by moben** [comment]
Writing out the `#define MIRYOKU_TABLE_...` in the org source feels a bit verbose, I'll look at how to generate them better with babel while rebasing #24

**Comment by manna-harbour** [comment]
Very nice!

Unfortunately I won't be making any more changes until after the Miryoku reorganisation, as the babel stuff is being split off to better support other implementations.  Then I'll probably start with moving all the array contents into `#define`s in the `.h` as you've done for Base.  That'll make things cleaner anyway and might open up some possibilities for direct use from outside.  If you wouldn't mind rebasing after that we can revisit this then.

Thanks!

**Comment by manna-harbour** [comment]
> Then I'll probably start with moving all the array contents into `#define`s in the `.h` as you've done for Base. That'll make things cleaner anyway and might open up some possibilities for direct use from outside

This has been done now with the move to Miryoku Babel.  It can be used to easily substitute layers: manna-harbour/miryoku#47.

**Comment by manna-harbour** [comment]
Support for adding custom layers and removing layers has been added. See manna-harbour/miryoku#48.

Thanks again for the PR!

**Pull request closed without merging**
