### PR TITLE
Disabled Main Wrapping

### LINKED ISSUE #11: [Bug] Generating with org-babel-tangle litters empty main functions
Steps to reproduce:
-Open miryoku.org in emacs
-Run org-babel-tangle with C-c C-v t

Operating Systems:
-Arch Linux
-Mac 10.14

When generating with babel tangle, many files have an empty main function appended.
For example, the file /layouts/community/split_3x6_3/manna-harbour_miryoku/config.h:
```
int main() {
// generated from users/manna-harbour_miryoku/miryoku.org  -*- buffer-read-only: t -*-

#pragma once

#define LAYOUT_miryoku(\
       K00,   K01,   K02,   K03,   K04,          K05,   K06,   K07,   K08,   K09,\
       K10,   K11,   K12,   K13,   K14,          K15,   K16,   K17,   K18,   K19,\
       K20,   K21,   K22,   K23,   K24,          K25,   K26,   K27,   K28,   K29,\
       N30,   N31,   K32,   K33,   K34,          K35,   K36,   K37,   N38,   N39\
)\
LAYOUT_split_3x6_3(\
KC_NO, K00,   K01,   K02,   K03,   K04,          K05,   K06,   K07,   K08,   K09,   KC_NO,\
KC_NO, K10,   K11,   K12,   K13,   K14,          K15,   K16,   K17,   K18,   K19,   KC_NO,\
KC_NO, K20,   K21,   K22,   K23,   K24,          K25,   K26,   K27,   K28,   K29,   KC_NO,\
                     K32,   K33,   K34,          K35,   K36,   K37\
)
return 0;
}

```
This is a list of the files that have this appended to it:
keyboards/atreus/keymaps/manna-harbour_miryoku/config.h
keyboards/atreus/keymaps/manna-harbour_miryoku/keymap.c
keyboards/for_science/keymaps/manna-harbour_miryoku/config.h
keyboards/for_science/keymaps/manna-harbour_miryoku/keymap.c
keyboards/gergo/keymaps/manna-harbour_miryoku/config.h
keyboards/gergo/keymaps/manna-harbour_miryoku/keymap.c
keyboards/keebio/iris/keymaps/manna-harbour_miryoku/config.h
keyboards/keebio/iris/keymaps/manna-harbour_miryoku/keymap.c
keyboards/kyria/keymaps/manna-harbour_miryoku/config.h
keyboards/kyria/keymaps/manna-harbour_miryoku/keymap.c
keyboards/lily58/keymaps/manna-harbour_miryoku/config.h
keyboards/lily58/keymaps/manna-harbour_miryoku/keymap.c
keyboards/moonlander/keymaps/manna-harbour_miryoku/config.h
keyboards/moonlander/keymaps/manna-harbour_miryoku/keymap.c
keyboards/redox_w/keymaps/manna-harbour_miryoku/config.h
keyboards/redox_w/keymaps/manna-harbour_miryoku/keymap.c
layouts/community/60_ansi/manna-harbour_miryoku/config.h
layouts/community/60_ansi/manna-harbour_miryoku/keymap.c
layouts/community/ergodox/manna-harbour_miryoku/config.h
layouts/community/ergodox/manna-harbour_miryoku/keymap.c
layouts/community/ortho_4x12/manna-harbour_miryoku/config.h
layouts/community/ortho_4x12/manna-harbour_miryoku/keymap.c
layouts/community/ortho_5x15/manna-harbour_miryoku/config.h
layouts/community/ortho_5x15/manna-harbour_miryoku/keymap.c
layouts/community/planck_mit/manna-harbour_miryoku/config.h
layouts/community/planck_mit/manna-harbour_miryoku/keymap.c
layouts/community/split_3x5_3/manna-harbour_miryoku/config.h
layouts/community/split_3x5_3/manna-harbour_miryoku/keymap.c
layouts/community/split_3x6_3/manna-harbour_miryoku/config.h
layouts/community/split_3x6_3/manna-harbour_miryoku/keymap.c
users/manna-harbour_miryoku/config.h
users/manna-harbour_miryoku/manna-harbour_miryoku.c
users/manna-harbour_miryoku/manna-harbour_miryoku.h

### PR DESCRIPTION
**Pull request by RubioJr9**
Trying to set :main no globally did not work, so I did it per code block.

Closes #11

### CODE REVIEW

**Comment by manna-harbour** [comment]
Thanks!  Would you mind moving `:main no` to the end of the boiler plate augments and before `:tangle` _filename_ so that the filename is easier to change?

**Comment by RubioJr9** [comment]
All done!

**Comment by manna-harbour** [comment]
Thanks!

**Comment by manna-harbour** [comment]
Added, thanks!

**Pull request closed without merging**
