### PR TITLE
Adds 5x15 ortho layout

### PR DESCRIPTION
**Pull request by sonnius**
Add 5x15 layout

## Description

Adding a 5x15 ortho-linear layout for 75% keyboards.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by manna-harbour** [comment]
Thanks of your PR!  Sorry about the PR template, it's inherited from upstream.

Regarding the altered thumb key placement compared with 4x12, can you use them comfortably while still keeping your wrists straight? If simulate a 15 column board by spacing out a split 4x12 and then use the shifted thumb position it causes my wrists to bend, especially reaching out to the extended thumb keys.

**Comment by sonnius** [comment]
The proposed placement feels right for me, i guess it depends on the size of your hands a bit a well.
Would it be helpful to create two layouts where the 'altered thumb placement' is secondary so people can choose?

**Comment by manna-harbour** [comment]
I'd like to make a few small changes and add a couple of things like the optional thumbs. It's probably easier if I just do it directly and add you as co-author to the commit, rather than doing it as suggested changes in this PR.  Are you ok with that?

**Comment by sonnius** [comment]
no problem at all, thank you for the great layout :)

**Comment by manna-harbour** [comment]
Ok, great! Thanks again for the PR and let me know if you find any problems with my changes.

**Pull request closed without merging**
